import { cookies } from 'next/headers';
import { Theme, THEME_COOKIE_NAME } from '../components/ThemeToggle/constants';
import { ReactQueryProvider } from '../providers/ReactQueryProvider';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookie = await cookies();
  const theme = cookie.get(THEME_COOKIE_NAME)?.value || Theme.Light;

  return (
    <html lang="en" data-theme={theme}>
      <ReactQueryProvider>
        <body>{children}</body>
      </ReactQueryProvider>
    </html>
  );
}
